version: "3.3"
services:
  app:
    image: omarhosny102/plant-disease-detection
    container_name: plant-disease-detection-container
    ports:
      - "5000:5000"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge